# Generated by Django 5.1.4 on 2025-01-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_alter_product_content_productoftheweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoftheweek',
            name='is_active_bool',
            field=models.BooleanField(default=False),
        ),
    ]
