# Generated by Django 5.1.4 on 2025-01-26 22:19

import product_module.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_productoftheweek_is_active_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoftheweek',
            name='end_date',
            field=models.DateTimeField(default=product_module.models.default_end_date),
        ),
    ]
