# Generated by Django 5.1.4 on 2025-01-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_alter_productoftheweek_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoftheweek',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/product-of-the-week'),
        ),
    ]
