# Generated by Django 5.1.4 on 2025-01-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0009_productoftheweek_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoftheweek',
            name='background_image',
        ),
        migrations.AddField(
            model_name='productoftheweek',
            name='background_mage',
            field=models.ImageField(blank=True, null=True, upload_to='images/product_of_the_week/'),
        ),
    ]
