# Generated by Django 5.1.4 on 2025-01-28 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0010_remove_productoftheweek_background_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoftheweek',
            old_name='background_mage',
            new_name='background_image',
        ),
    ]
