# Generated by Django 5.1.4 on 2025-01-28 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0011_rename_background_mage_productoftheweek_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoftheweek',
            name='image',
        ),
    ]
