# Generated by Django 5.1.4 on 2025-02-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0013_remove_product_rating_product_avg_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcommentreview',
            name='rating',
            field=models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], max_length=1),
        ),
        migrations.AlterField(
            model_name='productcommentreview',
            name='status',
            field=models.IntegerField(choices=[(1, 'در انتظار تایید'), (2, 'پذیرش شده'), (3, 'رد شده')], default=1, max_length=1),
        ),
    ]
