# Generated by Django 5.1.4 on 2025-02-10 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0014_alter_productcommentreview_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcommentreview',
            name='rating',
            field=models.IntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productcommentreview',
            name='status',
            field=models.IntegerField(choices=[(1, 'در انتظار تایید'), (2, 'پذیرش شده'), (3, 'رد شده')], default=1),
        ),
    ]
