# Generated by Django 5.1.4 on 2025-02-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0015_alter_productcommentreview_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='calorie',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
