# Generated by Django 5.1.4 on 2025-02-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0016_product_calorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avg_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
