# Generated by Django 5.1.4 on 2025-02-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0017_alter_product_avg_rate_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avg_rate',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
