services:
  app:
    build: ./app
    restart: always
    expose:
      - "8000"
    volumes:
      - project_data:/app
      - static_files:/app/static_files
      - media_files:/app/media_files
    depends_on:
      - ghanbari_store_postgres
      - redis
    env_file:
      - .env
    networks:
      - ghanbari_store_app_network
      - ghanbari_store_nginx_network

  ghanbari_store_postgres:
    image: postgres:latest
    restart: always
    volumes:
      - ghanbari_store_postgresql:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - "5432"
    networks:
      - ghanbari_store_app_network

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - media_files:/app/media_files
      - static_files:/app/static_files
    networks:
      - ghanbari_store_nginx_network
    depends_on:
      - app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - ghanbari_store_app_network


volumes:
  ghanbari_store_postgresql:
  project_data:
  static_files:
  media_files:

networks:
  ghanbari_store_app_network:
  ghanbari_store_nginx_network:
