# Generated by Django 5.1.4 on 2025-02-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbasket',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
