# Generated by Django 5.1.4 on 2025-02-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0005_checkout_is_successful_alter_checkout_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='zip_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
