# Generated by Django 5.1.4 on 2025-02-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0006_alter_checkout_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
