# Generated by Django 5.1.4 on 2025-02-24 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0007_alter_checkout_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='order_basket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='order_module.orderbasket'),
        ),
    ]
