# Generated by Django 5.1.4 on 2025-03-02 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0008_alter_checkout_order_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='is_successful',
            new_name='is_successfull',
        ),
    ]
