# Generated by Django 5.1.4 on 2025-08-23 15:38

import datetime
import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
import product_module.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=127, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products')),
                ('short_description', models.CharField(blank=True, db_index=True, max_length=510, null=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text')),
                ('price', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('calorie', models.IntegerField(blank=True, null=True)),
                ('avg_rate', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('discount_percent', models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('price_with_discount', models.PositiveIntegerField(blank=True, null=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=127, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCommentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('rating', models.IntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('status', models.IntegerField(choices=[(1, 'در انتظار تایید'), (2, 'پذیرش شده'), (3, 'رد شده')], default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/products/extra-images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product_module.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOfTheWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(default=product_module.models.default_end_date)),
                ('is_active_bool', models.BooleanField(default=False)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='images/product_of_the_week/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_highlight', to='product_module.product')),
            ],
        ),
    ]
