# Generated by Django 5.1.4 on 2025-01-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
