# Generated by Django 5.1.4 on 2025-01-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0002_contactmodel_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailForNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
