# Generated by Django 5.1.4 on 2024-12-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.TextField(max_length=510),
        ),
    ]
