# Generated by Django 5.1.4 on 2024-12-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0002_alter_article_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=127, null=True, unique=True),
        ),
    ]
