# Generated by Django 5.1.4 on 2024-12-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('image', models.ImageField(null=True, upload_to='sliders/')),
                ('link_url', models.URLField(blank=True, null=True)),
                ('btn_text', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
