# Generated by Django 5.1.4 on 2025-08-23 15:38

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLinkBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(default='', max_length=62)),
                ('url', models.URLField(blank=True, max_length=400, null=True)),
                ('btn_text', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/banners')),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.CharField(choices=[('article_detail', 'صفحه جزئیات مقالات'), ('articles', 'صفحه مقالات'), ('profile_dashboard', 'صفحه پروفایل کاربر (داشبورد)')], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='images/site_logo/')),
                ('is_main_setting', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, max_length=31, null=True)),
                ('email', models.EmailField(blank=True, max_length=31, null=True)),
                ('copy_right', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('about_us', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text')),
                ('site_name', models.CharField(max_length=150)),
                ('site_url', models.CharField(max_length=255)),
                ('free_shipping_threshold', models.PositiveIntegerField(default=150)),
                ('transportation_rate', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('whatsup', 'Whatsup'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('github', 'GitHub')], max_length=50, unique=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/team_members')),
                ('full_name', models.CharField(max_length=127)),
                ('position', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='FooterLinkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('url_title', models.URLField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_link_items', to='site_settings_module.footerlinkbox')),
            ],
        ),
        migrations.CreateModel(
            name='BranchLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=127, null=True)),
                ('branch_address', models.CharField(max_length=511, null=True)),
                ('branch_phone', models.CharField(blank=True, max_length=63, null=True)),
                ('site_setting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='site_settings_module.sitesetting')),
            ],
        ),
    ]
