# Generated by Django 5.1.4 on 2024-12-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
