# Generated by Django 5.1.4 on 2024-12-29 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0005_useraddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='Province',
            new_name='province',
        ),
    ]
