# Generated by Django 5.1.4 on 2024-12-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0006_rename_province_useraddress_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/authors'),
        ),
    ]
