# Generated by Django 5.1.4 on 2025-01-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0009_user_is_verified_userotp_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_active_code',
        ),
        migrations.AlterField(
            model_name='userotp',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
