# Generated by Django 5.1.4 on 2025-01-11 13:46

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=127, null=True)),
                ('branch_address', models.CharField(max_length=511, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='images/site_logo/')),
                ('is_main_setting', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, max_length=31, null=True)),
                ('email', models.EmailField(blank=True, max_length=31, null=True)),
                ('copy_right', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('about_us', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text')),
                ('site_name', models.CharField(max_length=150)),
                ('site_url', models.CharField(max_length=255)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('whatsup', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
