# Generated by Django 5.1.4 on 2025-01-11 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings_module', '0002_branchlocation_site_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchlocation',
            name='site_setting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='site_settings_module.sitesetting'),
        ),
    ]
