# Generated by Django 5.1.4 on 2025-01-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings_module', '0003_alter_branchlocation_site_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchlocation',
            name='branch_phone',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
