# Generated by Django 5.1.4 on 2025-01-23 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings_module', '0004_branchlocation_branch_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLinkBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, max_length=400, null=True)),
                ('image', models.ImageField(upload_to='images/banners')),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.CharField(choices=[('article-detail', 'صفحه جزئیات مقالات'), ('articles', 'صفحه مقالات'), ('dashboard', 'صفحه پروفایل کاربر (داشبورد)')], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/team_members')),
                ('full_name', models.CharField(max_length=127)),
                ('position', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='FooterLinkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('url_title', models.URLField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_link_items', to='site_settings_module.footerlinkbox')),
            ],
        ),
    ]
