# Generated by Django 5.1.4 on 2025-02-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings_module', '0005_footerlinkbox_sitebanner_teammember_footerlinkitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebanner',
            name='btn_text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sitebanner',
            name='description',
            field=models.CharField(default='', max_length=62),
        ),
        migrations.AlterField(
            model_name='sitebanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/banners'),
        ),
        migrations.AlterField(
            model_name='sitebanner',
            name='position',
            field=models.CharField(choices=[('article-detail', 'صفحه جزئیات مقالات'), ('articles', 'صفحه مقالات')], max_length=150),
        ),
        migrations.AlterField(
            model_name='sitebanner',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
