# Generated by Django 5.1.4 on 2025-02-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings_module', '0006_sitebanner_btn_text_sitebanner_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebanner',
            name='position',
            field=models.CharField(choices=[('article_detail', 'صفحه جزئیات مقالات'), ('articles', 'صفحه مقالات')], max_length=150),
        ),
    ]
