# Generated by Django 5.1.4 on 2025-02-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings_module', '0007_alter_sitebanner_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='free_shipping_threshold',
            field=models.PositiveIntegerField(default=150),
        ),
    ]
