# Generated by Django 5.1.4 on 2025-02-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings_module', '0008_sitesetting_free_shipping_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='transportation_rate',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
