# Generated by Django 5.1.4 on 2025-03-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings_module', '0009_sitesetting_transportation_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('whatsup', 'Whatsup'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('github', 'GitHub')], max_length=50, unique=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='whatsup',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='youtube',
        ),
    ]
